storeRoot: C:/Users/Janekdererste/Desktop/geomesa-playground/store
eventsFile: C:/Users/Janekdererste/Projects/matsim/examples/scenarios/equil/output_events.xml.gz
networkFile: C:/Users/Janekdererste/Projects/matsim/examples/scenarios/equil/network.xml